channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.8.6
  - snakemake=6.12.3
  - ptpython=3.0.20
  - jupyter=1.0.0
  - r-base=4.0.5
  - r-irkernel=1.3
  - r-tidyverse=1.3.1
  - r-wesanderson=0.3.6
