channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.8.6
  - snakemake=6.12.3
  - ptpython=3.0.20
  - jupyter=1.0.0
  - r-base=3.6.3
  - r-irkernel
  - scikit-allel=1.3.5
  - zarr=2.11.3
  - bedtools=2.30.0
