# Sample IDs as list
samples: ../resources/sequencedPlants_phenotypesHabitat.txt
chromosomes: ../resources/chromosome_file.txt
gff: ../resources/TrR.v5.renamed_reformated.gtf.gz

results_prefix: /home/santang3/scratch/gwsd/results
raw_read_prefix: /home/santang3/scratch/gwsd/raw_reads 
temp_dir: /home/santang3/scratch/gwsd/tmp 

# Samples to exclude based on QC (e.g., different species, low coverage, etc.) 
lowQual_samples_to_exclude: ['s_7_14', 's_54_9', 's_97_4', 's_23_12', 's_23_17']
related_samples_to_exclude: ['s_97_9', 's_37_18', 's_37_11', 's_42_3', 's_42_1', 's_83_11']

# Populations with multiple individuals
pops_multi_ind: ['40', '41', '42', '43', '97', '7', '23', '37', '54', '83', '116']

# Parameters for variant calling and SFS estimation with ANGSD
angsd:
  max_dp: 2600  # 2 x mean coverage from qualimap x # samples
  min_dp_ind_sfs: 1
  min_dp_ind_gl: 3

cluster:
  cores_per_node: 32

freebayes:
  nchunks: 500
