# Sample IDs as list
samples: ../resources/sequencedPlants_phenotypesHabitat.txt
chromosomes: ../resources/chromosome_file.txt

results_prefix: ../results
raw_read_prefix: /scratch/santang3/data 
temp_dir: /scratch/n/nessrobe/santang3/toronto_gwsd/tmp 

files:
  reference_genome: /scratch/n/nessrobe/santang3/clover-ref/ref_genome/GCA_005869975.1_AgR_To_v5_genomic.fna
  gff: /scratch/n/nessrobe/santang3/data/clover-ref/TrR.v5.renamed_reformated.gtf.gz

# Samples to exclude based on QC (e.g., different species, low coverage, etc.) 
lowQual_samples_to_exclude: ['s_7_14', 's_54_9', 's_97_4', 's_23_12', 's_23_17']
related_samples_to_exclude: ['s_97_9', 's_37_18', 's_37_11', 's_42_3', 's_42_1', 's_83_11']

# Populations with multiple individuals
pops_multi_ind: ['40', '41', '42', '43', '97', '7', '23', '37', '54', '83', '116']

freebayes:
  sample: s_7_7
  nodes_per_chrom: 12
  cores_per_node: 40
